#!/usr/bin/env bash
# This script installs and configures Nginx

# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a custom index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx without using systemctl
sudo service nginx restart
