#!/bin/env bash

# Display listening sockets for TCP and UDP
netstat -tuln | awk '/^Proto/ {print $0} /^tcp/ || /^udp/ {print $0}' | column -t

# Display active UNIX domain sockets (only servers)
netstat -lx | awk '/^Active UNIX domain sockets/ {print $0} /^unix/ {print $0}' | column -t
