#!/bin/env bash

# Function to display usage
display_usage() {
    echo "Usage: $0 {IP_ADDRESS}"
}

# Check if argument is provided
if [ $# -ne 1 ]; then
    display_usage
    exit 1
fi

# Ping the IP address 5 times
ping -c 5 $1
