#!/usr/bin/env bash

# Script that pings an IP address passed as an argument
# Accepts a string as an argument
# Pings the IP five times
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
# If no argument is passed

if [ $# -eq 0 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
elif [ $# -gt 1]; then 
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
else
	ping "$1" -c 5
fi
