Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.boot_timeout = 600  # Increase the boot timeout to 10 minutes
  config.vm.provision "file", source: "./0-nginx_likes_port_80", destination: "/home/vagrant/0-nginx_likes_port_80"
  config.vm.provision "shell", inline: <<-SHELL
    chmod +x /home/vagrant/0-nginx_likes_port_80
    sudo /home/vagrant/0-nginx_likes_port_80
  SHELL
end
