#!/usr/bin/env bash
# This script installs and configures Apache

# Update package lists
apt-get update

# Install Apache
apt-get install -y apache2

# Start Apache service
service apache2 start

# Create "Hello Holberton" page
echo "Hello Holberton" > /var/www/html/index.html
